#! /bin/bash
# postinst script
#

set -e

case "$1" in
	configure)

            # we remove extrausers from alternc-nss original package
	    sed -ie "s/ extrausers//" /etc/nsswitch.conf
            
	;;

	abort-upgrade|abort-remove|abort-deconfigure)

	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac
