#! /bin/bash
# postinst script
#

set -e

case "$1" in
	configure)

		echo -e "\033[31m**********************************************"
		echo "*                                            *"
		echo "*   ALTERNC          ACTION REQUESTED        *"
		echo "*                                            *"
		echo "* Please :                                   *"
		echo "*   run alternc.install to fully update      *"
		echo "*   update your ssl quota from admin panel   *"
		echo "*                                            *"
		echo "**********************************************"
		echo -e "\033[0m"

	;;

	abort-upgrade|abort-remove|abort-deconfigure)

	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac