#! /bin/bash
# postinst script
#

set -e

CONFIGFILE="/etc/alternc/local.sh"
LOGIN_SHELL="/bin/false"

case "$1" in
	configure)

		sed -ie '/^passwd:/ {/extrausers/! s/\(.*\)/\1 extrausers/}' /etc/nsswitch.conf
		sed -ie '/^group:/ {/extrausers/! s/\(.*\)/\1 extrausers/}' /etc/nsswitch.conf
		sed -ie '/^shadow:/ {/extrausers/! s/\(.*\)/\1 extrausers/}' /etc/nsswitch.conf

		# Set default login shell
		grep -Eq "^ *LOGIN_SHELL=" $CONFIGFILE || echo "
# Set a login shell to use by default
# default is /bin/false
LOGIN_SHELL=${LOGIN_SHELL}" >> $CONFIGFILE

		echo -e "\033[31m**********************************************"
		echo "*                                            *"
		echo "*   ALTERNC          ACTION REQUESTED        *"
		echo "*                                            *"
		echo "* Please :                                   *"
		echo "*   run alternc.install to fully update      *"
		echo "*   update your ssl quota from admin panel   *"
		echo "*                                            *"
		echo "**********************************************"
		echo -e "\033[0m"

	;;

	abort-upgrade|abort-remove|abort-deconfigure)

	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac
