#!/usr/bin/env -S bash -c 'type php-alternc-wrapper 1>/dev/null 2>&1 && exec php-alternc-wrapper $0 || exec php $0'
<?php

if (isset($argv[1]) && $argv[1] == "end") {
    chdir("/usr/share/alternc/panel/");
    require("/usr/share/alternc/panel/class/config_nochk.php");

    // Super admin enabled
    $admin->enabled=1;

    $nss->update_files();
}
