#!/usr/bin/php
<?php

if (isset($argv[1]) && $argv[1] == "end") {
    chdir("/usr/share/alternc/panel/");
    require("/usr/share/alternc/panel/class/config_nochk.php");

    // Super admin enabled
    $admin->enabled=1;

    $nss->update_files();
}
